artifacts:
  raw_data_path: "./data/raw/"
  processed_data_path: "./data/processed/"
  files_path: "./artifacts/files/"
  train_models: "./artifacts/checkpoints/train_models/"
  best_model: "./artifacts/checkpoints/best_model/"
  metrics_path: "./artifacts/metrics/"
  train_images: "./artifacts/outputs/train_images/"
  test_image: "./artifacts/outputs/test_image/"

dataloader:
  image_path: "./data/raw/dataset.zip"
  image_channels: 3
  image_size: 128
  batch_size: 8
  split_size: 0.30

TransUNet:
  nheads: 4
  num_layers: 2
  dim_feedforward: 512
  dropout: 0.5
  activation: "gelu"
  layer_norm_eps: 1e-05
  bias: False

trainer:
  epochs: 100
  lr: 0.0002
  optimizer: "AdamW"
  optimizers:
    Adam: 
      beta1: 0.9
      beta2: 0.999
      weight_decay: 0.0
    SGD: 
      momentum: 0.95
      weight_decay: 0.0
    AdamW:
      beta1: 0.9
      beta2: 0.999
      weight_decay: 1e-1
  loss: 
    type: "bce"
    loss_smooth: 1e-06
    alpha_focal: 0.75
    gamma_focal: 2
    alpha_tversky: 0.75
    beta_tversky: 0.5
  l1_regularization: False
  elastic_net_regularization: False
  verbose: True
  device: "mps"
  use_diff_attn: False       
  lam: 0.5   # Ideally 0.3-0.5 is better                

tester:
  dataset: "test"
  device: "mps"